TODO: Seanpm2001-GitHub-Pages-Collection
File: /.todo.yml
Tasks: [
  Maintenance: [
    Metadata: "Add metadata" [
      Tags: "Add tags"
      Link: "Add URL"
      Other: "Add other metadata"
    ];
    README: "Update README.md file" [
      Changes: [
        Icon: "Add icon"
        Desc: "Improve description"
        List: "List GitHub Pages projects with local links"
        Other: "Other/Unspecified"
      ];
      Other: "Other/Unspecified"
    ];
  ];
  Updates: [
    UpdateDesc: "Update GitHub Pages projects"
    Requirement: "Finish maintenance steps, and publish a release first"
  ];
];
# File info
# File type: YAML source file (*.yml *.yaml)
# File version: 1 (2022, Tuesday, August 16th at 9:02 pm PST)
# Line count (including blank lines and compiler line): 29
